### ISSUE TITLE
求微信群

### ISSUE THREAD

**Issue by Cyberhan123** [chokcoco/iCSS#115]

**Comment by xxholly32** [comment]
1

**Comment by chokcoco** [comment]
微信群超过了 200 人，没法扫码加入了，想加微信群的可以加我微信 coco1s，我拉大家进群~
@xxholly32 @Cyberhan123

**Comment by chokcoco** [comment]
![9](https://user-images.githubusercontent.com/8554143/134319850-d225a225-1d5f-4226-adf3-0c70bdca7457.gif)
