### ISSUE TITLE
想要请问一下，页面刷新后如何让页面加载完在一起显示呢？我现在用的方法感觉不是很好。

### ISSUE THREAD

**Issue by 1211ciel** [chokcoco/iCSS#193]
```
body {
    display: none;
}
```
我现在是设置 body 为none 然后加载完了再 显示出来
```
$(function () {
    $("body").show(33)
})
```
但有时 页面还是会左右抖动一下，不知道为什么。。

请问这个有更好的方法吗？谢谢啦

**Comment by chokcoco** [comment]
1、首先你得知道什么时候页面加载完，上面你的代码中是没有体现的（譬如某个重要的请求加载完毕）
2、在整个页面上通过 fixed 定位叠加一层白色背景的 div，遮住背后的所有正常元素，这个 fixed 定位的 div 中间有个转圈的 Loading 动画，一直转就行不需要考虑什么时候停
3、在（1）完成后，隐藏（2）中的 div，让背后的正常页面元素展现出来即可
> 这不是提问的仓库哈，如果还有其它问题，请加我微信 coco1s，本 Issue 关闭了~

**Comment by 1211ciel** [comment]
@chokcoco 谢谢。
