### ISSUE TITLE
请问SCSS在编译成CSS的时候Random是如何处理的？

### ISSUE THREAD

**Issue by 1234567Yang** [chokcoco/iCSS#251]
作者你好，看到你[这篇文章](https://github.com/chokcoco/iCSS/issues/247)以后我一直有一个疑问：
这篇文章里的SCSS的随机字符是如何实现不断转变的？
像是这个：
<img src="https://camo.githubusercontent.com/c90ebae817a81c7dfe1c6a892ca3abd0df8b739d574c27a46131979b74c3f6af/68747470733a2f2f70332d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f35383330313539306665316534323665613137373565383263643638323266397e74706c762d6b3375316662706663702d6a6a2d6d61726b3a303a303a303a303a7137352e696d616765233f773d36303026683d32353026733d3135363634333526653d67696626663d31303626623d303030303030">

因为我不是很懂SCSS，但是听说在运行时会把SCSS编译成CSS，然后**不会编译出js文件**。但是既然是运行时编译的，那么里面的随机字符应该在编译之后已经固定了，它是如何实现不断改变数字的呢？

说到底，就是SCSS里的Random到底是怎么实现的？

**Comment by bigshans** [comment]
跟 random 没什么关系吧？多读一下“结合 background-clip: text 实现文字效果”这一节。

**Comment by 1234567Yang** [comment]
> 跟 random 没什么关系吧？多读一下“结合 background-clip: text 实现文字效果”这一节。

那些随机变化的颜色和字符？

**Comment by bigshans** [comment]
> > 跟 random 没什么关系吧？多读一下“结合 background-clip: text 实现文字效果”这一节。
> 
> 那些随机变化的颜色和字符？

伪随机，用 scss 提前生成好就可以了。

**Comment by 1234567Yang** [comment]
对啊SCSS转成CSS是提前生成好的，但是它是怎么在客户端CSS搁那变化字符的呢？
按理说应该是随机字符和颜色，但是静止不动，不会变
请问大佬是我哪里理解错了吗？

**Comment by chokcoco** [comment]
SCSS 的 Random 函数编译完成后，其实值就是确定的。
对于运行时而言，转化成了 CSS 后，值就不会再发生改变了。
只是对于类似与 CodePen 这种在线提供 SCSS 语法的平台，在线编译运行的平台，每次刷新的结果都是不一样的。但是对于上线业务，在每次打包构建编译的时候，值就确定了，不会因为每次刷新浏览器得到不一样的值。
