### ISSUE TITLE
请问小程序《store by.jpg》进入以后 上半部分根据陀螺仪实现的碰撞元素 该实现呀。

### ISSUE THREAD

**Issue by dudylan** [chokcoco/iCSS#261]
如题

**Comment by dudylan** [comment]
store by.jpg 这个是小程序的名字

**Comment by chokcoco** [comment]
如果是真心提问，建议带上录屏或者带上 GIF，讲讲自己的思考和疑惑点。
而不是简单的扔个小程序的名字~

**Comment by dudylan** [comment]
抱歉，前面的提问有些考虑不周。

以下是录屏
https://github.com/chokcoco/iCSS/assets/34180156/b223ff46-f3bd-4344-9060-28c3e80bc65e

视频内容上方像是一个盒子一样 然后元素通过手机的方向 来控制元素运动。
我认为这个功能应该分为两部分。

1. 根据陀螺仪来控制 元素应该往哪个方向运动。
2. 识别元素的边界。然后有元素的碰撞，重力弹力，惯性。

我也查了相关的资料。 有找到一个圆形的边缘碰撞的demo。 里面涉及了前面说的第二点。
但学习起来还是有些吃力。
demo 链接
https://wow.techbrood.com/fiddle/1175

demo 中 使用了box2d.js 的库

然后是我想基于demo 能把不规则的元素的边界找到。 然后对接陀螺仪的参数。就完成了。

**Comment by dudylan** [comment]
https://github.com/kripken/box2d.js  
box2d.js 库链接

**Comment by chokcoco** [comment]
> 抱歉，前面的提问有些考虑不周。
> 
> 以下是录屏 https://github.com/chokcoco/iCSS/assets/34180156/b223ff46-f3bd-4344-9060-28c3e80bc65e
> 
> 视频内容上方像是一个盒子一样 然后元素通过手机的方向 来控制元素运动。 我认为这个功能应该分为两部分。
> 
> 1. 根据陀螺仪来控制 元素应该往哪个方向运动。
> 2. 识别元素的边界。然后有元素的碰撞，重力弹力，惯性。
> 
> 我也查了相关的资料。 有找到一个圆形的边缘碰撞的demo。 里面涉及了前面说的第二点。 但学习起来还是有些吃力。 demo 链接 https://wow.techbrood.com/fiddle/1175
> 
> demo 中 使用了box2d.js 的库
> 
> 然后是我想基于demo 能把不规则的元素的边界找到。 然后对接陀螺仪的参数。就完成了。

看了下视频，确实挺有意思，不过确实也需要一定的工作量。

核心是Canvas+陀螺仪，不规则的元素的边界我觉得可以简单处理，大致有比较粗糙的轮廓（类似于 SVG 的 path 即可），不过类型的动画我没什么经验，可能给不到太大帮助。

**Comment by dudylan** [comment]
好的。谢谢您的回答。 我自行研究一下。
