### ISSUE TITLE
提供个素材，web安全问题

### ISSUE THREAD

**Issue by fanerge** [chokcoco/iCSS#35]
#  a链接的安全问题
阐述问题：当a链接有target="_blank"属性时，必须添加rel="noreferrer noopener"，不然新产生的页面可以通过window.opener来获取到父窗口的window对象。
```
<a href="www.baidu.com" target="_blank" rel="noreferrer noopener" >
```
[聊聊 rel=noopener](https://juejin.im/post/5950f387f265da6c44072d6c)
[关于a标签target=“_blank"使用rel=noopener](https://juejin.im/post/5addbf3bf265da0b78682131)

**Comment by gylidian** [comment]
才知道有这种东西qwq...

**Comment by chokcoco** [comment]
很好的知识，不过我这个项目基本是关于CSS的哈。
